trigger:
- main

variables:
  resourceGroup: 'Devoir-1'
  location: 'eastus'
  templateFile: 'template.json'
  parametersFile: 'parameters.json'

stages:
- stage: Deploy
  jobs:
  - job: DeployVM
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        azureSubscription: 'f8ee07ed-b563-4b27-931f-56bdf1405242'  # Remplace par ton nom de connexion Azure
        resourceGroupName: $(resourceGroup)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: $(templateFile)
        csmParametersFile: $(parametersFile)
        deploymentMode: 'Incremental'
